#!/bin/sh

ln -sf /lib/systemd/system/mod-midi-merger.service /etc/systemd/system/multi-user.target.wants
ln -sf /lib/systemd/system/mod-midi-broadcaster.service /etc/systemd/system/multi-user.target.wants
#DEBHELPER#
